// Generated by Rebtel Atelier. Edit via the workbench or by hand — both are respected.

import type { Variant } from "@rebtel-atelier/spec";

export const buttonVariants: Variant[] = [
  {
    id: "primary",
    name: "Primary",
    extends: "base",
    draft: {},
    published: {
      bg: { token: "color.button-primary-bg" },
      fg: { token: "color.button-primary-text" },
      border: { token: "color.button-primary-border" },
      radius: { token: "radius.lg" },
    },
    publishedVersion: 2,
  },
  {
    id: "secondary",
    name: "Secondary",
    extends: "base",
    draft: {},
    published: {
      bg: { token: "color.button-secondary-black-bg" },
      fg: { token: "color.button-secondary-black-text" },
      border: { token: "color.button-secondary-black-border" },
      radius: { token: "radius.md" },
    },
    publishedVersion: 1,
  },
  {
    id: "ghost",
    name: "Ghost",
    extends: "base",
    draft: {},
    published: {
      bg: { token: "color.button-ghost-bg" },
      fg: { token: "color.button-ghost-text" },
      border: { token: "color.button-ghost-border" },
      radius: { token: "radius.md" },
    },
    publishedVersion: 1,
  },
];
