import type { Component, PropValue, TokenRef, Variant } from "@rebtel-atelier/spec";

const HEADER =
  "// Generated by Rebtel Atelier. Edit via the workbench or by hand — both are respected.\n";

function isTokenRef(v: unknown): v is TokenRef {
  return (
    v !== null &&
    typeof v === "object" &&
    !Array.isArray(v) &&
    "token" in (v as object) &&
    typeof (v as { token: unknown }).token === "string" &&
    // A TokenRef is exactly { token: string } — extra keys mean it's a
    // generic object, not a reference. Keeps serialization predictable.
    Object.keys(v as object).length === 1
  );
}

function indentLine(depth: number): string {
  return "  ".repeat(depth);
}

/**
 * Serialize a PropValue to TypeScript source. Deterministic object-key
 * ordering (insertion order) so the same variant spec always produces the
 * same bytes. Matches Prettier's defaults (double quotes, trailing commas
 * on multi-line blocks, 2-space indent).
 */
function serializeValue(value: PropValue, depth: number): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (isTokenRef(value)) {
    return `{ token: ${JSON.stringify(value.token)} }`;
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const inner = value
      .map((item) => `${indentLine(depth + 1)}${serializeValue(item, depth + 1)},`)
      .join("\n");
    return `[\n${inner}\n${indentLine(depth)}]`;
  }

  // Plain object.
  const entries = Object.entries(value as Record<string, PropValue>);
  if (entries.length === 0) return "{}";
  const inner = entries
    .map(
      ([k, v]) =>
        `${indentLine(depth + 1)}${formatKey(k)}: ${serializeValue(v, depth + 1)},`,
    )
    .join("\n");
  return `{\n${inner}\n${indentLine(depth)}}`;
}

/** TS-style key: bare identifier where safe, quoted string otherwise. */
function formatKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}

/** Strip runtime-only fields before emitting to the shipped file. */
function variantForEmit(v: Variant) {
  return {
    id: v.id,
    name: v.name,
    extends: v.extends,
    draft: {} as Record<string, PropValue>,
    published: v.published,
    publishedVersion: v.publishedVersion,
  };
}

/** componentId → camelCase variable-name prefix (Button → button, etc.). */
function componentIdToSlug(id: string): string {
  if (id.length === 0) return id;
  return id[0]!.toLowerCase() + id.slice(1);
}

export function variantsVarNameFor(component: Component): string {
  return `${componentIdToSlug(component.id)}Variants`;
}

/** Path-in-repo for a component's variants file. */
export function variantsFilePathFor(component: Component): string {
  return `packages/rebtel-ds/src/components/${component.id}/${component.id}.variants.ts`;
}

export interface GenerateVariantFileOptions {
  component: Component;
}

/**
 * Deterministic serializer for a component's variants file. Given the
 * current in-memory Component (post-publish, draft empty, new version
 * already set), produce the exact TS source that should land in
 * `packages/rebtel-ds/src/components/<ComponentName>/<ComponentName>.variants.ts`.
 *
 * Stability guarantees:
 * - Variant order follows the Variant[] insertion order.
 * - Object keys within each variant follow their declaration order.
 * - Token refs always emit as `{ token: "..." }` (one-line form).
 * - publishedHistory, lastPublishedAt, lastPublishedBy are stripped —
 *   those are runtime pin state, not source of truth for engineers.
 * - draft always emits as `{}` — shipped files don't carry editor drafts.
 *
 * Re-running on the same input produces byte-identical output, so
 * publishing the same variant twice yields a clean no-op diff rather
 * than reshuffling the whole file.
 */
export function generateVariantFile({ component }: GenerateVariantFileOptions): string {
  const varName = variantsVarNameFor(component);
  const emitVariants = component.variants.map(variantForEmit);

  const serializedArray = emitVariants
    .map((v) => `${indentLine(1)}${serializeValue(v, 1)},`)
    .join("\n");

  const body =
    emitVariants.length === 0
      ? `export const ${varName}: Variant[] = [];\n`
      : `export const ${varName}: Variant[] = [\n${serializedArray}\n];\n`;

  return `${HEADER}\nimport type { Variant } from "@rebtel-atelier/spec";\n\n${body}`;
}
