import type {
  Component,
  ComponentOverrideSnapshot,
  PropValue,
  TokenRef,
} from "@rebtel-atelier/spec";

const HEADER =
  "// Generated by Rebtel Atelier. Edit via the workbench or by hand — both are respected.\n";

function isTokenRef(v: unknown): v is TokenRef {
  return (
    v !== null &&
    typeof v === "object" &&
    !Array.isArray(v) &&
    "token" in (v as object) &&
    typeof (v as { token: unknown }).token === "string" &&
    Object.keys(v as object).length === 1
  );
}

function indentLine(depth: number): string {
  return "  ".repeat(depth);
}

/** TS-style key: bare identifier where safe, quoted string otherwise. */
function formatKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}

/**
 * Serialize a PropValue to TypeScript source. Deterministic — object
 * keys preserve insertion order, token refs always emit single-line as
 * `{ token: "..." }`. Re-running on the same input produces byte-
 * identical output (no hash codes, no timestamps, no Maps).
 */
function serializeValue(value: PropValue, depth: number): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (isTokenRef(value)) {
    return `{ token: ${JSON.stringify(value.token)} }`;
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const inner = value
      .map((item) => `${indentLine(depth + 1)}${serializeValue(item, depth + 1)},`)
      .join("\n");
    return `[\n${inner}\n${indentLine(depth)}]`;
  }

  const entries = Object.entries(value as Record<string, PropValue>);
  if (entries.length === 0) return "{}";
  const inner = entries
    .map(
      ([k, v]) =>
        `${indentLine(depth + 1)}${formatKey(k)}: ${serializeValue(v, depth + 1)},`,
    )
    .join("\n");
  return `{\n${inner}\n${indentLine(depth)}}`;
}

function componentIdToSlug(id: string): string {
  if (id.length === 0) return id;
  return id[0]!.toLowerCase() + id.slice(1);
}

export function componentVarNameFor(component: Component): string {
  return `${componentIdToSlug(component.id)}Component`;
}

/**
 * Path-in-repo for a component's spec file. v4 collapses the legacy
 * three-files-per-component into two — only `.tsx` and `.spec.ts`.
 */
export function componentSpecFilePathFor(component: Component): string {
  return `packages/rebtel-ds/src/components/${component.id}/${component.id}.spec.ts`;
}

// Backwards-compatible export name — the route still imports
// variantsFilePathFor by name. v3 lived in `<Name>.variants.ts`; v4
// lives in `<Name>.spec.ts`. The export name keeps callers from
// re-importing during the chunk-2 transition; 3.5b cleans up the name.
export const variantsFilePathFor = componentSpecFilePathFor;
export const variantsVarNameFor = componentVarNameFor;

export interface GenerateVariantFileOptions {
  component: Component;
}

/**
 * Deterministic serializer for a v4 component's `.spec.ts` file. Given
 * the post-publish Component (draft empty, version bumped, history
 * populated), produce TS source that matches what would land at
 * `packages/rebtel-ds/src/components/<Name>/<Name>.spec.ts`.
 *
 * Stability guarantees:
 * - axisOverrides emit in insertion order. Same for stateOverrides.
 * - Object keys within each props bag preserve insertion order.
 * - Token refs always emit one-line as `{ token: "..." }`.
 * - publishedHistory, lastPublishedAt, lastPublishedBy, baseDraft, draft
 *   are stripped — those are runtime / editor-local state, not the
 *   committed truth.
 *
 * Re-running on the same input produces byte-identical output.
 *
 * Chunk-2 caveat: the generated file does NOT import the migration
 * plan (the hand-authored .spec.ts files do — they share axes and
 * supportedStates with the migration plans). The generator inlines
 * axes / supportedStates as literals. 3.5b's serializer rewrite will
 * either (a) lift the plan import or (b) consolidate the source of
 * truth so the generated file matches the hand-authored shape exactly.
 */
export function generateVariantFile({ component }: GenerateVariantFileOptions): string {
  const varName = componentVarNameFor(component);

  const axesLiteral = serializeValue(
    component.axes.map((a) => ({
      name: a.name,
      options: [...a.options],
      default: a.default,
    })) as unknown as PropValue,
    1,
  );
  const supportedStatesLiteral = serializeValue(
    component.supportedStates as unknown as PropValue,
    1,
  );

  const baseSpecLiteral = serializeValue(
    {
      kind: "primitive",
      id: component.baseSpec.id,
      type: component.baseSpec.type,
      props: component.baseSpec.props,
      children: component.baseSpec.children as unknown as PropValue,
    } as unknown as PropValue,
    1,
  );

  const draftLiteral = serializeValue(
    { axisOverrides: [], stateOverrides: [] } as unknown as PropValue,
    1,
  );

  const publishedLiteral = serializeValue(
    serializableSnapshot(component.published) as unknown as PropValue,
    1,
  );

  const propSchemaLine = component.propSchema
    ? `\n${indentLine(1)}propSchema: ${serializeValue(component.propSchema as unknown as PropValue, 1)},`
    : "";
  const hideFamilyViewLine = component.hideFamilyView
    ? `\n${indentLine(1)}hideFamilyView: true,`
    : "";

  const body =
    `export const ${varName}: Component = {\n` +
    `${indentLine(1)}id: ${JSON.stringify(component.id)},\n` +
    `${indentLine(1)}name: ${JSON.stringify(component.name)},\n` +
    `${indentLine(1)}paletteGroup: ${JSON.stringify(component.paletteGroup)},\n` +
    `${indentLine(1)}axes: ${axesLiteral},\n` +
    `${indentLine(1)}supportedStates: ${supportedStatesLiteral},\n` +
    `${indentLine(1)}baseSpec: ${baseSpecLiteral},\n` +
    `${indentLine(1)}draft: ${draftLiteral},\n` +
    `${indentLine(1)}published: ${publishedLiteral},\n` +
    `${indentLine(1)}publishedVersion: ${component.publishedVersion},${propSchemaLine}${hideFamilyViewLine}\n` +
    `};\n`;

  return `${HEADER}\nimport type { Component } from "@rebtel-atelier/spec";\n\n${body}`;
}

function serializableSnapshot(s: ComponentOverrideSnapshot): {
  axisOverrides: { axisSelection: Record<string, string>; props: Record<string, PropValue> }[];
  stateOverrides: { state: string; props: Record<string, PropValue> }[];
} {
  return {
    axisOverrides: s.axisOverrides.map((o) => ({
      axisSelection: { ...o.axisSelection },
      props: { ...o.props },
    })),
    stateOverrides: s.stateOverrides.map((o) => ({
      state: o.state,
      props: { ...o.props },
    })),
  };
}
