import { describe, it, expect } from "vitest";
import type { Component } from "@rebtel-atelier/spec";
import { generateVariantFile } from "./generateVariantFile.js";

const buttonComponent: Component = {
  id: "Button",
  name: "Button",
  paletteGroup: "inputs",
  version: 1,
  baseSpec: {
    id: "Button:base",
    type: "Button",
    variant: null,
    props: {},
    children: [],
  },
  variants: [
    {
      id: "primary",
      name: "Primary",
      extends: "base",
      draft: { radius: { token: "radius.lg" } }, // draft should NOT appear in output
      published: {
        bg: { token: "color.button-primary-bg" },
        fg: { token: "color.button-primary-text" },
        border: { token: "color.button-primary-border" },
        radius: { token: "radius.md" },
      },
      publishedVersion: 2,
      publishedHistory: {
        // history should NOT appear in output
        1: { bg: { token: "old.bg" } },
        2: { bg: { token: "color.button-primary-bg" } },
      },
      lastPublishedAt: "2026-04-22T10:00:00Z",
      lastPublishedBy: "forrest",
    },
  ],
};

describe("generateVariantFile", () => {
  it("includes the header comment", () => {
    const out = generateVariantFile({ component: buttonComponent });
    expect(out.startsWith("// Generated by Rebtel Atelier.")).toBe(true);
  });

  it("emits token refs inline as { token: \"...\" }", () => {
    const out = generateVariantFile({ component: buttonComponent });
    expect(out).toContain(`bg: { token: "color.button-primary-bg" }`);
  });

  it("uses the camelCase variants var name", () => {
    const out = generateVariantFile({ component: buttonComponent });
    expect(out).toContain("export const buttonVariants: Variant[]");
  });

  it("strips draft, publishedHistory, lastPublishedAt, lastPublishedBy", () => {
    const out = generateVariantFile({ component: buttonComponent });
    expect(out).not.toContain("publishedHistory");
    expect(out).not.toContain("lastPublishedAt");
    expect(out).not.toContain("lastPublishedBy");
    // draft is emitted as an empty object marker — present but always {}.
    expect(out).toContain("draft: {}");
    // And the draft values from the input must not leak through.
    expect(out).not.toContain("radius.lg");
  });

  it("is deterministic — same input produces byte-identical output", () => {
    const a = generateVariantFile({ component: buttonComponent });
    const b = generateVariantFile({ component: buttonComponent });
    expect(a).toBe(b);
  });

  it("handles empty variants array", () => {
    const empty: Component = { ...buttonComponent, variants: [] };
    const out = generateVariantFile({ component: empty });
    expect(out).toContain("export const buttonVariants: Variant[] = [];");
  });

  it("preserves variant insertion order", () => {
    const multi: Component = {
      ...buttonComponent,
      variants: [
        {
          id: "zulu",
          name: "Zulu",
          extends: "base",
          draft: {},
          published: {},
          publishedVersion: 1,
        },
        {
          id: "alpha",
          name: "Alpha",
          extends: "base",
          draft: {},
          published: {},
          publishedVersion: 1,
        },
      ],
    };
    const out = generateVariantFile({ component: multi });
    expect(out.indexOf('id: "zulu"')).toBeLessThan(out.indexOf('id: "alpha"'));
  });
});
